# Config map file to setup the environment for a MongoDB Service in a Pod
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  mongo-url: mongo-service # url to connect to the MongoDB service